EyeSeeTea/glass-dev

- i18n/en.pot
- src/webapp/components/calls-history/CallsHistoryContent.tsx
- src/webapp/components/calls-history/CallsTable.tsx
- src/webapp/components/country-information/CountryInformationContent.tsx
- src/webapp/components/current-call/UploadsTable.tsx
- src/webapp/components/custom-card/CustomCard.tsx
- src/webapp/components/landing-content/LandingNews.tsx
- src/webapp/components/landing-content/YourNotifications.tsx
- src/webapp/components/upload-history/UploadHistoryContent.tsx
- src/webapp/hooks/useSidebarMenus.tsx
- src/webapp/pages/Router.tsx
- src/webapp/pages/calls-history/CallsHistoryPage.tsx
- src/webapp/pages/country-information/CountryInformationPage.tsx
- src/webapp/pages/current-call/CurrentCallPage.tsx
- src/webapp/pages/data-submission/DataSubmissionPage.tsx
- src/webapp/pages/upload-history/UploadHistoryPage.tsx
-   **Issue:** https://app.clickup.com/t/860pe95q5
- create global reusable card components to display each country info
- few code cleanup from existing components and pages
###: squashed commits
init country information page
doc: todo note
set home link to current-call
add title prop to CustomCard
> Code clean-up and wrap-up country information ui

- src/webapp/components/upload/UploadFiles.tsx
-   **Issue:** Closes [Remove "None" as an option for BatchID and use Dataset 1 as the default option](https://app.clickup.com/t/860pwnuhk)
- Remove the "none" option from batchId dropdown and default it to the first available option
*N/A*
> remove none option & default first available dataset

- src/webapp/components/upload/UploadRis.tsx
- src/webapp/components/upload/UploadSample.tsx
-   **Issue:** Closes [[Bug Report] Trying to remove a file before I upload is not working](https://app.clickup.com/t/860q53dcy)
- I couldn't replicate the error, but I uploaded a file mimicking an error in the upload, tried to remove it and it didn't work, that behaviour is fixed with this PR
*N/A*
> solve bug where x doesnt do anything when there was a bad upload

- src/webapp/components/app-bar/GlassAppBar.tsx
- src/webapp/components/data-file-history/Filter.tsx
- src/webapp/components/upload/UploadFiles.tsx
- src/webapp/components/user-profile/UserSettingsContent.tsx
-   **Issue:** Closes [Dancing dropdowns bug](https://app.clickup.com/t/860q0gexr)
- Fix selects on open adding padding to body. This solution requires to add the MenuProps for future Selects, since I couldn't find a way to bypass this with css on the MUI theme
> fix: add fix to selects to not add padding on body, on open

- src/domain/entities/Questionnaire.ts
- src/webapp/components/questionnaire/QuestionInput.tsx
- src/webapp/components/questionnaire/widgets/NumberWidget.tsx
-   **Issue:** Closes [Questionnaire rules 2](https://app.clickup.com/t/860rzea48)
```
{
"dataElementCodesLowerToHigher": {
"AMR_GLASS_ACUTE_CARE_NUMBER": "AMR_AMR_ACUTE_CARE_NUMBER",
"AMR_GLASS_HOSPITALS_NUMBER": "AMR_AMR_HOSPITALS_NUMBER",
"AMR_GLASS_INPATIENT_ADM_NUMBER": "AMR_AMR_INPATIENT_ADM_NUMBER",
"AMR_GLASS_INPATIENT_DAY_NUMBER": "AMR_AMR_INPATIENT_DAY_NUMBER",
"AMR_GLASS_OUTPATIENT_CONS_NUMBER": "AMR_AMR_OUTPATIENT_CONS_NUMBER"
},
"type": "sectionValuesHigherThan"
}
```
[Screencast from 22-11-23 14:30:26.webm](https://github.com/EyeSeeTea/glass-dev/assets/49402898/5c1c3d33-572b-49d4-a96f-3d0c096d7015)
> Add new rule higher than to questionnaire and show validation error message

- src/domain/usecases/data-entry/amr/ImportRISFile.ts
- src/domain/usecases/data-entry/amr/ImportSampleFile.ts
- src/domain/usecases/data-entry/utils/getCategoryOptionCombo.tsx
- src/domain/usecases/data-entry/utils/includeBlockingErrors.ts
-   **Issue:** Closes https://app.clickup.com/t/86942fc56, https://app.clickup.com/t/86942fc94
1. If attributeOptionCombo, categoryOptionCombo are not found, show blocking errors and do not proceed.
2. Trim whitespaces when file parsing for AMR 
https://github.com/EyeSeeTea/glass-dev/assets/83749675/d67b8ad5-aa5e-4570-a75a-15da5ee88986
> blocking err on category option combo not found, trim codes on file parsing

- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
-   **Issue:** Closes #? https://app.clickup.com/t/8693yfefj
-  #8693yfefj
1. set event date of AMR-I and AMR-F events to sample date column
2. if sample date not found, set to 1st Jan of the period.
IMPORTANT!
This PR should be accompanied by adding AMR_GLASS_AMR_DET_SAMPLE_DATE dataelement to AMR - Individual Program, AMR - data Stage. https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/programSection/program/mMAj6Gofe49
> fix: set the event date to 01-01 of period

- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
-   **Issue:** Closes #?https://app.clickup.com/t/86945qz0y
- 86945qz0y
1.  fix string on year incorrect error for AMR-I & AMR-F
>  fix string on year incorrect error for AMR-I & AMR-F

- src/domain/entities/GlassAtcVersionData.ts
- src/domain/entities/data-entry/amc/ProductRegistryAttributes.ts
- src/domain/entities/data-entry/amc/RawProductConsumption.ts
- src/domain/usecases/data-entry/amc/CalculateConsumptionDataProductLevelUseCase.ts
- src/domain/usecases/data-entry/amc/CalculateConsumptionDataSubstanceLevelUseCase.ts
- src/domain/usecases/data-entry/amc/CustomValidationsAMCProductData.ts
- src/domain/usecases/data-entry/amc/ImportAMCProductLevelData.ts
- src/domain/usecases/data-entry/amc/RecalculateConsumptionDataProductLevelForAllUseCase.ts
- src/domain/usecases/data-entry/amc/RecalculateConsumptionDataSubstanceLevelForAllUseCase.ts
- src/domain/usecases/data-entry/amc/utils/__tests__/data/productRegistryAttributesBasic.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/productRegistryAttributesConcVolumeAndVolume.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/productRegistryAttributesMillionInternationalUnitDifferentDDDUnit.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/productRegistryAttributesNoCombCodeNoFoundDDD.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/productRegistryAttributesUnitDoseCombCode.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/productRegistryAttributesWrongStrengthUnit.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/rawProductConsumption.json
- src/domain/usecases/data-entry/amc/utils/calculationConsumptionProductLevelData.ts
- src/domain/usecases/data-entry/amc/utils/getConsumptionDataProductLevel.ts
- src/domain/usecases/data-entry/amc/utils/getConsumptionDataSubstanceLevel.ts
-   **Issue:** Closes #8694gde4d [Changes to the AMC calculations](https://app.clickup.com/t/8694gde4d)
**METADATA CHANGES in dev-238 (NOT IN APDV):**
- change data element [AMR_GLASS_AMC_DET_PACKAGES](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/dataElementSection/dataElement/yQ23GizXyTe) by [AMR_GLASS_AMC_DET_PACKAGES_MANUAL](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/dataElementSection/dataElement/yimWSvsiGhi) in [program stages AMC - Raw Product Consumption in programs AMC - Product Register](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/programSection/program/G6ChA5zMW9n)
- Name changed to [this DE](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/programSection/tra …
> Changes to the AMC calculations

- src/data/repositories/data-entry/AMCProductDataDefaultRepository.ts
- src/domain/entities/data-entry/amc/ProductDataTrackedEntity.ts
- src/domain/repositories/data-entry/AMCProductDataRepository.ts
- src/domain/usecases/data-entry/amc/CalculateConsumptionDataProductLevelUseCase.ts
-   **Issue:** Closes #8694p3z6j [Bug: packages autocalculated](https://app.clickup.com/t/8694p3z6j)
- Filter products by period to use in calculations
METADATA CHANGES:
Following changes in https://app.clickup.com/t/8694ap3qu, also I would like to propose that inside the zip in atc_ddd_index.json all units that are millions international unit, the code should be MIU like in the [option set of measure units](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/otherSection/optionSet/iSiwVc3bAgi/options) (zip attached with new data required). And also according to salt and units inside atc_ddd_index.json, in the [option set of salt ](https://dev.eyeseetea.com/who-dev-238/dhis-web-maintenance/index.html#/edit/otherSection/optionSet/qOCslKTMCBM/options)the following …
> Bug: packages autocalculated

- src/data/repositories/MetadataDefaultRepository.ts
- src/domain/repositories/MetadataRepository.ts
- src/domain/usecases/data-entry/ImportBLTemplateEventProgram.ts
-   **Issue:** Closes #8694mxmkh https://app.clickup.com/t/8694mxmkh
1. Recursively parse also metadata ids(programs, data elements, tracked entity attributes) that occur in error messages
AMC File with error : 
[AMC-Product Level Data-DZA-TEMPLATE (3).xlsx](https://github.com/EyeSeeTea/glass-dev/files/15480079/AMC-Product.Level.Data-DZA-TEMPLATE.3.xlsx)
EGASP File with error :
[EGASP-THA-2023-ERR.xlsx](https://github.com/EyeSeeTea/glass-dev/files/15480090/EGASP-THA-2023-ERR.xlsx)
> feat: improve import error message parsing

- i18n/en.pot
- i18n/es.po
- src/domain/usecases/data-entry/amc/CustomValidationsAMCProductData.ts
-   **Issue:** Closes #8694rjm8n [Bug: Got errors on A07AA and P01AB but no product with these codes in the file](https://app.clickup.com/t/8694rjm8n)
- Fix validation of ATC codes level 4 and improve error messages
[AMC-Product Level Data-THA-TEMPLATE (2).xlsx](https://github.com/user-attachments/files/15626955/AMC-Product.Level.Data-THA-TEMPLATE.2.xlsx)
[AMC - WIDP_Product Register_20240531_TEST_FRA_2022_WITHOUT_A07_P01AB.xlsx](https://github.com/user-attachments/files/15628383/AMC.-.WIDP_Product.Register_20240531_TEST_FRA_2022_WITHOUT_A07_P01AB.xlsx)
> Bug: Got errors on A07AA and P01AB but no product with these codes in the file

- src/domain/entities/Questionnaire.ts
- src/webapp/components/questionnaire/widgets/NumberWidget.tsx
-   **Issue:** Closes #8694rjkcm ,   https://app.clickup.com/t/8694rjkcm
1. Configure error message in datastore, for rules with  value of one data element should be less than value of another data element.
2. Implement rule for data element value less than const
3. Implement rule for data element value double of another
4. Fix : reset question values if section is hidden
the following should be the rules value in datastore Glass --> Modules -->  
{"name": "AMR", 
questionnaires : [
"id": "OYc0CihXiSn", 
rules : <value below> 
]
} 
```
"rules": [
{
"dataElementCode": "AMR_AMR_ACUTE_CARE_NUMBER",
"constValue": "100",
"type": "questionValueLessThanConst",
"errorMessage": "Number of acute-care facilities should be more than 100"
},
{
"dataElementCode": "AMR_AMR_HOSPITALS_NUMBER", …
```
> AMR AGG Implementation Questionnaire new validation rules

- src/data/repositories/data-entry/DataValuesDefaultRepository.ts
- src/domain/usecases/data-entry/amr/ImportRISFile.ts
- src/domain/usecases/data-entry/amr/ImportSampleFile.ts
- src/domain/usecases/data-entry/utils/checkDuplicateRows.ts
- src/domain/usecases/data-entry/utils/includeBlockingErrors.ts
- src/domain/usecases/data-entry/utils/mapDhis2Summary.ts
-   **Issue:** Closes #8694m1xdn,    https://app.clickup.com/t/8694m1xdn
1. Add a pre import check to detect duplicates in rows of SAMPLE and RIS files for AMR AGG files.
https://github.com/EyeSeeTea/glass-dev/assets/83749675/d9799801-9171-4662-b3dc-dae0ecf5c3a6
Files with duplicates which will give duplicate detected blocking error for POLAND 2022 DS1 : 
[GLASS_Salmonella_2022_corrected_DS1-RIS.xlsx](https://github.com/user-attachments/files/15896375/GLASS_Salmonella_2022_corrected_DS1-RIS.xlsx)
[POL_2022_SAMPLE.txt](https://github.com/user-attachments/files/15896374/POL_2022_SAMPLE.txt)
> fix: duplicate row detection for AMR AGG Ris and Sample files

- src/domain/usecases/data-entry/amr/ImportRISFile.ts
- src/domain/usecases/data-entry/amr/ImportSampleFile.ts
- src/domain/usecases/data-entry/utils/mapDhis2Summary.ts
…red' error
1. On delete action, do not run consistency checks
2. On delete action, even if some imports are ignored, do not show error.
> fix: On delete, do not run consistency checks and ignore 'import ignored' error

- src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataAtcNotFound.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataBasic.json
- [Fix wrong type of tests data for substance calculations tests](https://github.com/EyeSeeTea/glass-dev/commit/6262ab366313049e9952b48f779520f309b32e26)
> Fix wrong type of tests data for substance calculations tests

- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_reset_sample.ts
- src/scripts/amr_agg_data_validation.ts
- src/scripts/amr_agg_data_validation_sample.ts
Fixes TS2345 type error, which prevents the code from compiling.
Ensure auth credentials are defined before passing to D2ApiArgs
This PR addresses an issue where `username` and `password` could be `undefined`, causing a type error. The solution ensures that both `username` and `password` are defined before passing them to `D2ApiArgs`.
- Used nullish coalescing operator (??) to provide default empty string values if `username` or `password` are `undefined`.
> Added auth validation

- src/domain/usecases/data-entry/egasp/CustomValidationForEventProgram.ts
-   **Issue:** Closes #86952w25p [Bug: Upload substance data: 0 errors but cannot continue](https://app.clickup.com/t/86952w25p)
- Check if there are any error before add ATC error to blocking errors array
[AMC-Substance Level Data-FRA-TEMPLATE (2).xlsx](https://github.com/user-attachments/files/16249359/AMC-Substance.Level.Data-FRA-TEMPLATE.2.xlsx)
> Bug: Upload substance data: 0 errors but cannot continue

- src/CompositionRoot.ts
- src/data/repositories/GlassATCDefaultRepository.ts
- src/domain/entities/GlassAtcVersionData.ts
- src/domain/entities/data-entry/amc/RawSubstanceConsumptionCalculated.ts
- src/domain/entities/data-entry/amc/SubstanceConsumptionCalculated.ts
- src/domain/repositories/GlassATCRepository.ts
- src/domain/usecases/data-entry/ImportBLTemplateEventProgram.ts
- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/ImportSecondaryFileUseCase.tsx
- src/domain/usecases/data-entry/amc/ImportAMCSubstanceLevelData.ts
- src/domain/usecases/data-entry/amc/utils/calculationConsumptionSubstanceLevelData.ts
- src/domain/usecases/data-entry/egasp/CustomValidationForEventProgram.ts
- src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
-   **Issue:** Closes #86952w1wd [Bug: ATCVersion substance level data](https://app.clickup.com/t/86952w1wd)
- Allow to upload year in atc version manual for substance files and save the last atc version key in event program
-Raw:
- Calculated:
-Error:
[2018_AFG_NOT_OK_AMC-Substance Level Data-AFG-TEMPLATE.xlsx](https://github.com/user-attachments/files/16284384/2018_AFG_NOT_OK_AMC-Substance.Level.Data-AFG-TEMPLATE.xlsx)
[2018_AFG_OK_AMC-Substance Level Data-AFG-TEMPLATE.xlsx](https://github.com/user-attachments/files/16284385/2018_AFG_OK_AMC-Substance.Level.Data-AFG-TEMPLATE.xlsx)
> Bug: ATCVersion substance level data

- src/domain/entities/GlassAtcVersionData.ts
-   **Issue:** Closes #869567a21 [ATC Classification Updates for 2024](https://app.clickup.com/t/869567a21)
- Give priority to fully ATC codes in aware classification than atc prefixes: for instance J01XX05 is in OTH but J01XX05 still matches the rule for ATB (J01*). So giving the priority to full code, J01XX05 will be classified ad OTH not ATB.
> ATC Classification Updates for 2024

- src/domain/usecases/data-entry/ImportBLTemplateEventProgram.ts
- src/domain/usecases/data-entry/egasp/CustomValidationForEventProgram.ts
-   **Issue:** Closes #869565hb8 [No error line number in concistency checks](https://app.clickup.com/t/869565hb8)
- Add lines when there is an error in the ATC version manual
BEFORE:
AFTER:
[WITH_ERRORS_AMC-Substance Level Data-AFG-TEMPLATE.xlsx](https://github.com/user-attachments/files/16363048/WITH_ERRORS_AMC-Substance.Level.Data-AFG-TEMPLATE.xlsx)
> No error line number in concistency checks

- src/domain/entities/data-entry/amc/ProductRegistryAttributes.ts
- src/domain/entities/data-entry/amc/RawProductConsumption.ts
- src/domain/entities/data-entry/amc/RawSubstanceConsumptionCalculated.ts
- src/domain/entities/data-entry/amc/RawSubstanceConsumptionData.ts
- src/domain/entities/data-entry/amc/SubstanceConsumptionCalculated.ts
- src/domain/usecases/data-entry/amc/utils/calculationConsumptionProductLevelData.ts
- src/domain/usecases/data-entry/amc/utils/calculationConsumptionSubstanceLevelData.ts
- Change domain entities according to mandatory data elements in programs
- Adapt calculations code to those changes
1. AMC - Product Register and in AMC - Product Register-APDV programs --> AMC - Raw Substance Consumption Calculated program stage:
Compulsory data elements:
- AMR_GLASS_AMC_DET_ATC_AUTOCALCULATED
- AMR_GLASS_AMC_DET_ROUTE_ADMIN_AUTOCALCULATED	
- AMR_GLASS_AMC_DET_SALT_AUTOCALCULATED
- AMR_GLASS_AMC_DET_SECTOR_AUTOCALCULATED
- AMR_GLASS_AMC_DET_LEVEL_AUTOCALCULATED
- AMR_GLASS_AMC_DET_ATC_VERSION_AUTOCALCULATED
- AMR_GLASS_AMC_DET_DATA_STATUS_AUTOCALCULATED
2. AMC - Raw Substance Consumption Data program and AMC - Raw Substance Consumption Data-APDV program
Compulsory data elements:
- AMR_GLASS_AMC_DET_ATC_MANUAL
- …
> Fix mandatory fields for calculations and adapt code

- src/webapp/components/upload/ReviewDataSummary.tsx
- src/webapp/hooks/useCurrentDataSubmissionId.ts
-   **Issue:** Closes #? https://app.clickup.com/t/8697c0fnf, #8697c0fnf
1. Wait for  get specific data submission to be fetched before loading page.
2. The get specific data submission hook was using promises, refactored to use futures.
3. Change from step 3 (Review data summary) to step 4 (completion screen) only after updating the data submission status to "COMPLETE" (Data to be approved by country)
https://github.com/user-attachments/assets/239c1341-5fa1-4338-a83f-4d888516e3f5
.
> set complete status before moving to step 4

- src/webapp/components/current-data-submission/Questionnaires.tsx
- src/webapp/components/questionnaire/QuestionnaireActions.tsx
- src/webapp/components/questionnaire/QuestionnaireForm.tsx
I need to fix the rendering and position of the Questionnaire description as a quick fix to be able to have fixed text appear for the users in the Questionnaires to indicate notes of usage for the user. I hope to replace this with a better fix soon.
> Add css to render the questionnaire description and position it below questionnaire + remove it from questionnaire card

- src/webapp/components/reports/EmbeddedReport.tsx
-   **Issue:** Closes #8698ybqy7 [Reports not showing since DHIS2 upgrade](https://app.clickup.com/t/8698ybqy7)
- Add height in iframe for dashboard version 2.41
[Screencast from 2025-05-05 11-10-48.webm](https://github.com/user-attachments/assets/04168da7-1480-48b9-bf01-e366cd3b391f)
> Reports not showing since DHIS2 upgrade

- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
- src/domain/usecases/data-entry/utils/checkSpecimenPathogen.ts
-   **Issue:** Closes https://app.clickup.com/t/8698yjt72 #8698yjt72
Replicated to AMR-I the same specimen/pathogen/antibiotic validation applied in the AMR-Aggregated.
**NOTE**: The validation is based on dataStore configuration, so it **requires changes to the dataStore**: 
In the `/glass/modules` key, look in the array for the object with name `AMR - individual`. In that object, add the `consistencyChecks` property, with the contents cloned from the same `consistencyChecks` from the `AMR` module.
I'm including a full JSON backup in the linked issue.
> AMR-I: Add consistency checks for specimen/pathogen/antibiotic

- src/domain/usecases/data-entry/amc/CustomValidationsAMCProductData.ts
- src/domain/usecases/data-entry/egasp/CustomValidationForEventProgram.ts
-   **Issue:** May be related to: 
- https://app.clickup.com/t/8699apv1h
- https://app.clickup.com/t/8699apxx8
- Period validation was failing for negative GMT offset timezones. i.e. GMT-3. 
- When uploading a document that contains a row for 2024 and the selected period is 2024, the upload was failing, with blocking validation errors regarding period (unexpected)
- When uploading a document that contains a row for 2025 and the selected period is 2024, the upload would work, no validation errors (unexpected)
- This specific case, of rows with a date outside the period, may lead to problem with rows not being removed and duplicates later in the flow, when approving/requesting changes/deleting/submitting/approving.
- For example, if `eventDate` === `new Date('2024-01-01')`
- `(new …
> fix: checkPeriod validation for timezones with negative GMT offsets

- i18n/en.pot
- i18n/es.po
- src/data/repositories/amc-questionnaires/AMCQuestionnaireD2Repository.ts
- src/domain/entities/amc-questionnaires/AMCQuestionnaire.ts
- src/webapp/components/current-data-submission/amc-questionnaires/MainPageAMCQuestionnaires.tsx
- src/webapp/components/current-data-submission/amc-questionnaires/useMainPageAMCQuestionnaire.ts
- src/webapp/context-providers/AMCQuestionnaireContextProvider.tsx
-   **Issue:** Related https://app.clickup.com/t/869900zzw
- Add error handling when loading Questionnaire forms
- Handle errors in mappings from Events to Domain entities (if some fields are missing or incomplete in the Event)
- Validate business rules and throw error when creating an `AMCQuestionnaire`
- Show an error message with details
This was previously unhandled, now a message is displayed. This is useful for having more details into what and why the error is happening. Now it may be due to trying to view Questionnaires created before schema changes around Stratum (should only happen in dev). In the future it might be useful if bad data is created through bulk-upload. 
The next step, if needed, would be to let the user fix the errors within the app, but it would require more work …
> fix: handle AMC Questionnaire loading errors

- src/data/repositories/amc-questionnaires/QuestionsAMCQuestionnaireD2Repository.ts
- src/data/repositories/amc-questionnaires/getAMCQuestionnaireProgramMetadata.ts
- src/domain/entities/amc-questionnaires/AMCQuestionnaireQuestions.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/amClassAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/componentAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/generalAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/mapperUtils.ts
- src/webapp/components/form/FormSection.tsx
- src/webapp/components/form/InfoTooltip.tsx
- src/webapp/components/form/presentation-entities/FormFieldsState.ts
-   **Issue:** Closes https://app.clickup.com/t/8699n78kg #8699n78kg
This PR updates the display text to always show the Form Name. If a Description is present, an "info" icon appears next to the name. Clicking the icon opens a tooltip showing the description, matching the behavior in the Capture App as requested.
Additionally, the * required field indicator is now red during form editing, for consistency with Capture (this was not requested but thought it was a good idea).
- Change mappings to use `displayFormName` as `text` and `displayDescription` as `description` in `AMCQuestion` for both TEAs and DEs
- Add new optional prop `infoTooltipText` to `FormFieldStateBase`, that when set will render the `InfoTooltip` component.
- Change mappings from `AMCQuestion` to `FormFieldState`:
- …
> feat: AMC questionnaire description icon and text

- src/data/repositories/amc-questionnaires/DataSourceOptionsD2Repository.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/amClassAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/generalAMCQuestionnaireMapper.ts
-   **Issue:** https://app.clickup.com/t/8699n9max
It would also be nice to understand why we have the ids of the optionSets hard coded in the system. This change was needed because we needed to use a new multi-choice optionSet but we still need to make changes in the code for this.
> AMC Data Questionnaire fixes - Change Id of OptionSet and Change names of sections

- src/domain/usecases/data-entry/amr-individual-fungal/RISIndividualFungalFileValidations.ts
- src/domain/usecases/data-entry/amr-individual-fungal/common.ts
-   **Issue:** Closes https://app.clickup.com/t/8699n7b1g #8699n7b1g
- add `checkSpecimenDate` and `checkAdmissionDate`
- refactor: move individual row validations to `RISIndividualFungalFileValidations.ts` to avoid creating a summary for each validation type
This PR includes only the validations, but realized that `CustomDataColumns["value"]`  is typed as `string | number | undefined` even though it contains `Date` objects in case the column contains a date value. Also types are not enforced because of usage of `any` in `getProgramMetadata`, called from `common.ts`. We might want to improve this, specially if we find any date-related issues.
> feat: add AMR-I validations

- i18n/en.pot
- i18n/es.po
- src/data/repositories/CaptureFormDefaultRepository.ts
- src/domain/usecases/data-entry/ear/ImportSignalsUseCase.tsx
- src/utils/dates.ts
- src/webapp/components/new-signal/ProgramQuestionnaireForm.tsx
-   **Issue:** Closes https://app.clickup.com/t/8699h0rdu #8699h0rdu
- Tracker import was failing because the dates were not formatted as YYYY-MM-DD. Added formatting for that.
- Improved error handling: there was an uncaught Error after the import failure. 
- Added a check for the import status and the existance of `bundleReport`.
- Added handling of these errors in the view to show a more specific message rather than the default one about permissions.
- After an Error, the user was redirected to the previous screen. Removed these `hideForm()` calls so the user stays in the form in case of save failure.
- Created common utils for parsing and formatting the date as YYYY-MM-DD using the current user locale. 
- Only implemented in these related areas. We might want to use these in other …
> fix: EAR save error

- src/webapp/components/current-data-submission/amc-questionnaires/getComponentAMCQuestionnaireFormEntity.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/amClassAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/componentAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/generalAMCQuestionnaireMapper.ts
- src/webapp/components/current-data-submission/amc-questionnaires/mappers/mapperUtils.ts
-   **Issue:** Closes https://app.clickup.com/t/8699gzr37 #8699gzr37
- change yes/no options to radio buttons instead of checkbox
- only `sameAsUNPopulation` was changed 
- although AM Class questions in the general form are yes/no options, we keep using checkboxes for them
- extract method `getOptionCodeFromFieldValue`
> fix: change yes/no options to radio buttons

- src/webapp/components/form/widgets/MultipleSelector.tsx
- src/webapp/components/form/widgets/Selector.tsx
-   **Issue:** Closes https://app.clickup.com/t/8699yqck9 #8699yqck9
- Set popover properties, based on this comment: `https://github.com/mui/material-ui/issues/12208#issuecomment-406820537`
- Minor manual adjustments to margin and min-height for improved visual layout
Notes:  
- When there is no room below the dropdown, the items will accomodate to the viewport and may show above the dropdown
- Tried different approaches to always show the menu below, but I couldn't find an easy way to accomplish that, and I think these changes are a good tradeoff. Let me know if we still want to do that.
- I tried setting a `maxHeight` for the menuItems, but finally discarded it.
- For the number of options we are handling we are ok
- Using `maxHeight` worsens the UX because the scroll isn't obvious and …
> fix: make Selector widgets items display below the control
