- src/webapp/components/main-layout/MainLayout.tsx
- src/webapp/utils/helpers.ts
-   **Issue:** Closes [Make logout button from side panel in Home Page work](https://app.clickup.com/t/860pfkjfb)
- dhis2 logout based on landing-page-app
*Not applied*
> Make logout button from side panel in Home Page work

- i18n/en.pot
- i18n/es.po
- package.json
- src/CompositionRoot.ts
- src/data/data-store/DataStoreKeys.ts
- src/data/repositories/GlassNewsDefaultRepository.ts
- src/domain/entities/GlassNews.ts
- src/domain/repositories/GlassNewsRepository.ts
- src/domain/usecases/GetGlassNewsUseCase.ts
- src/domain/usecases/ValidateGlassNewsUseCase.ts
- src/webapp/components/landing-content/LandingNews.tsx
- src/webapp/hooks/useGlassNews.ts
- yarn.lock
-   **Issue:** Closes [News from GLASS in Home Page to be retrieved from the backend](https://app.clickup.com/t/860pfkhw3)
- Create **News** key on Datastore json to store landing page news, fetch the data, adapt the news component and add dayjs library in order to format the date coming from backend.
> News from GLASS in Home Page to be retrieved from the backend

- i18n/es.po
- src/CompositionRoot.ts
- src/data/data-store/DataStoreKeys.ts
- src/data/repositories/GlassSubmissionsDefaultRepository.ts
- src/domain/entities/GlassSubmissions.ts
- src/domain/repositories/GlassSubmissionsRepository.ts
- src/domain/usecases/GetGlassSubmissionsUseCase.ts
- src/domain/usecases/ValidateGlassSubmissionsUseCase.ts
- src/webapp/components/upload-history/UploadHistoryContent.tsx
- src/webapp/components/upload-history/UploadTable.tsx
- src/webapp/components/upload-history/UploadTableBody.tsx
- src/webapp/hooks/useGlassSubmissions.ts
-   **Issue:** Closes [Retrieve the submission information for the upload history from the submissions key in the datastore](https://app.clickup.com/t/860phxadj)
- Fetch data from dhis2 datastore submissions key and populate table list of "upload history" page
Edit! New image of table:
> Fetch upload history data from submissions in dhis2

- i18n/es.po
- src/CompositionRoot.ts
- src/data/data-store/DataStoreKeys.ts
- src/data/repositories/GlassSubmissionsDefaultRepository.ts
- src/domain/entities/GlassSubmissions.ts
- src/domain/repositories/GlassSubmissionsRepository.ts
- src/domain/usecases/GetGlassSubmissionsUseCase.ts
- src/domain/usecases/ValidateGlassSubmissionsUseCase.ts
- src/webapp/components/current-call/DataSubmissionSteps.tsx
- src/webapp/components/current-call/ListOfDatasets.tsx
- src/webapp/components/current-call/UploadsTable.tsx
- src/webapp/components/current-call/UploadsTableBody.tsx
- src/webapp/components/upload-history/UploadHistoryContent.tsx
- src/webapp/components/upload-history/UploadTable.tsx
- src/webapp/components/upload-history/UploadTableBody.tsx
- src/webapp/hooks/useGlassSubmissions.ts
-   **Issue:** Closes [Retrieve the information for the "List of datasets" step in the current call page, from the submissions key in the datastore](https://app.clickup.com/t/860phz6rt)
- Fetch the subsmissions values for the Current Call's list of datasets and populate with datastore values.
> Retrieve the information for the "List of datasets" on Current Call page

- src/CompositionRoot.ts
- src/data/repositories/GlassDocumentsDefaultRepository.ts
- src/data/repositories/GlassUploadsDefaultRepository.ts
- src/domain/repositories/GlassDocumentsRepository.ts
- src/domain/repositories/GlassUploadsRepository.ts
- src/domain/usecases/DeleteDocumentInfoByUploadIdUseCase.tsx
- src/webapp/components/upload/UploadRis.tsx
- src/webapp/components/upload/UploadSample.tsx
-   **Issue:** Closes [Remove the document from both datastore and file resources+documents metadata when clicking the red cross in upload file section](https://app.clickup.com/t/860pvcnnh)
- Create a useCase for removing both the document entry to the dataStore, and the document related fields on the submissions entry.
*N/A*
> Delete document & upload info on file deletion (x)

- i18n/en.pot
- i18n/es.po
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
-   **Issue:** Closes #https://app.clickup.com/t/860q417vq?
Render row only if data is available
https://user-images.githubusercontent.com/83749675/223163534-486691dc-ee5b-4565-bd62-1f589d34b1e1.mp4
> do not show undefined in status overview summary

- i18n/en.pot
- src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
- src/domain/usecases/data-entry/ImportSampleFileUseCase.tsx
- src/domain/usecases/data-entry/utils/checkYear.ts
- src/webapp/components/upload/ConsistencyChecks.tsx
-   **Issue:** Closes https://app.clickup.com/t/860q416gw
If year in file does not match year of data submission, throw a blocking error and disable continue
> add custom validation - Year, for RIS and Sample file

- i18n/en.pot
- src/CompositionRoot.ts
- src/data/repositories/GlassDataSubmissionDefaultRepository.ts
- src/data/repositories/QuestionnaireD2Repository.ts
- src/domain/entities/data-entry/DataValuesSaveSummary.ts
- src/domain/repositories/GlassDataSubmissionRepository.ts
- src/domain/usecases/SetDataSubmissionStatusUseCase.ts
- src/webapp/components/current-data-submission/CurrentDataSubmissionContent.tsx
- src/webapp/components/current-data-submission/Questionnaires.tsx
- src/webapp/components/current-data-submission/UploadSteps.tsx
- src/webapp/components/questionnaire/QuestionnaireForm.tsx
- src/webapp/components/questionnaire/QuestionnaireFormTest.tsx
- src/webapp/hooks/useStatusDataSubmission.ts
- src/webapp/pages/current-data-submission/CurrentDataSubmissionPage.tsx
-   **Issue:** Closes https://app.clickup.com/t/860q4r82x
If all mandatory questionnaires are complete, then transition to DATA TO BE APPROVED BY COUNTRY.
If a Questionnaire is "Set to incomplete", then re-transition to NOT COMPLETED
> Implement transition between NOT COMPLETED and DATA TO BE APPROVED BY COUNTRY

- i18n/en.pot
- src/webapp/components/current-data-submission/CurrentDataSubmissionContent.tsx
- src/webapp/components/current-data-submission/Questionnaires.tsx
- src/webapp/components/current-data-submission/UploadSteps.tsx
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/current-data-submission/overview/Overview.tsx
- src/webapp/components/questionnaire/QuestionnaireActions.tsx
- src/webapp/hooks/useStatusDataSubmission.ts
- src/webapp/pages/current-data-submission/CurrentDataSubmissionPage.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/860q4r97h
Transition status from COMPLETE to PENDING APPROVAL on user confirmation
> Transition status from COMPLETE to PENDING APPROVAL on user confirmation

- i18n/en.pot
- src/CompositionRoot.ts
- src/data/repositories/DataValuesDefaultRepository.ts
- src/data/repositories/GlassDocumentsDefaultRepository.ts
- src/domain/entities/data-entry/DataValuesSaveSummary.ts
- src/domain/repositories/GlassDocumentsRepository.ts
- src/domain/repositories/data-entry/DataValuesRepository.ts
- src/domain/usecases/DownloadDocumentUseCase.ts
- src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
- src/domain/usecases/data-entry/ImportSampleFileUseCase.tsx
- src/webapp/components/current-data-submission/ListOfDatasets.tsx
- src/webapp/components/current-data-submission/StatusMap.ts
- src/webapp/components/current-data-submission/UploadSteps.tsx
- src/webapp/components/current-data-submission/UploadsTable.tsx
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/current-data-submission/overview/Overview.tsx
- src/webapp/components/current-data-submission/overview/StatusDetails.ts
- src/webapp/components/upload-history/UploadHistoryContent.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/hooks/useGlassUploads.ts
-   **Issue:** Closes https://app.clickup.com/t/860q4radh
> Add, download and delete dataset from data set list.

- i18n/en.pot
- src/webapp/components/upload/Completed.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/components/upload/ReviewDataSummary.tsx
- src/webapp/components/upload/UploadFiles.tsx
- src/webapp/components/upload/UploadSample.tsx
-   **Issue:** Closes [Connect uploads page with backend - Error issue](https://app.clickup.com/t/860q0g9b4)
- Fixed the change of status to the continue on the 3rd step, fixed the logic to change both ris and sample files
> Fix upload flow

- i18n/en.pot
- i18n/es.po
- src/CompositionRoot.ts
- src/data/repositories/GlassUploadsDefaultRepository.ts
- src/domain/repositories/GlassUploadsRepository.ts
- src/domain/usecases/GetGlassUploadsByModuleOUPeriodUseCase.ts
- src/webapp/components/current-data-submission/StatusMap.ts
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/current-data-submission/overview/Overview.tsx
- src/webapp/components/current-data-submission/overview/StatusDetails.ts
-   **Issue:** Closes [Workflow changes](https://app.clickup.com/t/860q0gvx6)
- Fetch uploads count to show on cards, UI changes, refactoring StatusMap and refactoring.
> Workflow changes

- i18n/en.pot
- i18n/es.po
- src/CompositionRoot.ts
- src/data/repositories/RISDataCSVRepository.ts
- src/data/repositories/SampleDataCSVRepository.ts
- src/data/repositories/utils/CSVUtils.ts
- src/domain/repositories/data-entry/RISDataRepository.ts
- src/domain/repositories/data-entry/SampleDataRepository.ts
- src/domain/usecases/data-entry/ValidateRISFileUseCase.tsx
- src/domain/usecases/data-entry/ValidateSampleFileUseCase.tsx
- src/webapp/components/upload/UploadRis.tsx
- src/webapp/components/upload/UploadSample.tsx
-   **Issue:** Closes https://app.clickup.com/t/860q9tq02
1. Make sure uploaded RIS and Sample files have all the columns in their respective formats.
> Add Integrity checks for RIS and SAMPLE files

- src/data/repositories/InstanceDefaultRepository.ts
- src/domain/entities/User.ts
- src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
- src/domain/usecases/data-entry/ImportSampleFileUseCase.tsx
- src/domain/usecases/data-entry/utils/checkCountry.ts
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/contexts/current-orgUnit-context.ts
-   **Issue:** Closes https://app.clickup.com/t/860q5dx75
1. Add country check as blocking error.
> Custom validation : Country in file should be same as one selected in interface

- i18n/en.pot
- i18n/es.po
- reviewpad.yml
- src/webapp/components/current-data-submission/ListOfDatasets.tsx
- src/webapp/components/current-data-submission/Questionnaires.tsx
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/sidebar-nav/SidebarNavMenu.tsx
- src/webapp/components/upload/Completed.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/components/upload/UploadFiles.tsx
- src/webapp/components/upload/UploadRis.tsx
- src/webapp/components/upload/UploadSample.tsx
- src/webapp/context-providers/CurrentPeriodContextProvider.tsx
- src/webapp/contexts/current-period-context.ts
- src/webapp/pages/Router.tsx
- src/webapp/pages/current-data-submission/CurrentDataSubmissionPage.tsx
- src/webapp/pages/upload/UploadPage.tsx
-   **Issue:** Closes https://app.clickup.com/t/860q52mfj
> Period Context and Query Param handling throughout the app

- reviewpad.yml
- src/data/repositories/InstanceDefaultRepository.ts
> view access fix

- src/webapp/components/current-data-submission/UploadsTableBody.tsx
-   **Issue:** Closes https://app.clickup.com/t/860qajcx3
> delete enabled on editmode statuses only

- i18n/en.pot
- i18n/es.po
- src/data/repositories/GlassDataSubmissionDefaultRepository.ts
- src/domain/entities/GlassDataSubmission.ts
- src/domain/usecases/GetSpecificDataSubmissionUseCase.ts
- src/webapp/components/current-data-submission/UploadsTable.tsx
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
-   **Issue:** Closes [Display full status history](https://app.clickup.com/t/860q2z1vj)
- Created dataStore values for statusHistory array, implement UI when pressed 'display full status history'
> Add full status history

- i18n/en.pot
- src/webapp/components/upload/UploadContent.tsx
- src/webapp/pages/upload/UploadPage.tsx
-   **Issue:** Closes https://app.clickup.com/t/860qajjwf
Go to step 1 of upload wizard if period, orgUnit or module changes
> Go to step 1 of upload wizard if period, orgUnit or module changes

- i18n/en.pot
- src/CompositionRoot.ts
- src/data/repositories/GlassDataSubmissionDefaultRepository.ts
- src/data/repositories/RISDataCSVRepository.ts
- src/data/repositories/SampleDataCSVRepository.ts
- src/domain/entities/GlassUploads.ts
- src/domain/repositories/GlassDataSubmissionRepository.ts
- src/domain/repositories/data-entry/RISDataRepository.ts
- src/domain/repositories/data-entry/SampleDataRepository.ts
- src/domain/usecases/SaveDataSubmissionsUseCase.ts
- src/domain/usecases/UploadDocumentUseCase.ts
- src/domain/usecases/ValidateGlassUploadsUseCase.ts
- src/domain/usecases/data-entry/ValidateRISFileUseCase.tsx
- src/domain/usecases/data-entry/ValidateSampleFileUseCase.tsx
- src/webapp/components/current-data-submission/ListOfDatasets.tsx
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/data-submissions-history/DataSubmissionsHistoryContent.tsx
- src/webapp/components/sidebar/SideBar.tsx
- src/webapp/components/upload-history/Filter.tsx
- src/webapp/components/upload-history/UploadHistoryContent.tsx
- src/webapp/components/upload/UploadRis.tsx
- src/webapp/components/upload/UploadSample.tsx
- src/webapp/entities/uploads.ts
- src/webapp/hooks/useGlassDataSubmissionsByModuleAndOU.ts
-   **Issue:** Closes https://app.clickup.com/t/860q7ectr
1. fix: show completed uploads in correct uploads and the rest in discarded table
2. fix: populate the records column in dataset table
3. Feature: Pre-populate data submission history & upload history for 5 years
> Completed vs Uploaded uploads, # of records, pre-populate histories.

- i18n/en.pot
- i18n/es.po
- src/data/repositories/DataValuesDefaultRepository.ts
- src/domain/repositories/data-entry/DataValuesRepository.ts
- src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
- src/domain/usecases/data-entry/ImportSampleFileUseCase.tsx
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/components/upload/ReviewDataSummary.tsx
- src/webapp/components/upload/UploadContent.tsx
-   **Issue:** Closes (https://app.clickup.com/t/860q6ac6h) , https://app.clickup.com/t/860q6ac6h
> dry run imports and import only if no blocking errors

- src/webapp/components/module-card/ModuleCard.tsx
-   **Issue:** Closes [Home page data-submissions are not populated with the uploaded files](https://app.clickup.com/t/860qd30vx)
- Show uploaded files & questionnaires info on module card in landing page.
> Add uploaded files & questionnaires info on modules card

- src/webapp/components/current-data-submission/UploadSteps.tsx
- src/webapp/components/sidebar/mapModuleToMenu.ts
-   **Issue:** Closes #?https://app.clickup.com/t/860qd2wq8
> Hide validations tab and reports menu until functionality is complete

- i18n/en.pot
- src/webapp/components/current-data-submission/ListOfDatasets.tsx
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/860qd2rh9
> Delete files with appropriate info message

- i18n/en.pot
- src/webapp/components/upload-history/UploadTable.tsx
- src/webapp/components/upload-history/UploadTableBody.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/860qd2uww
1. removed list icon in first column
2. removed row click behaviour
3. added download file handling
> upload history table on click behavior

- src/data/repositories/InstanceDefaultRepository.ts
-   **Issue:** Closes #?https://app.clickup.com/t/860qd2jmy
> fix: remove all countries with region NA

- i18n/en.pot
- src/webapp/components/current-data-submission/ListOfDatasets.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/85yw8j5gv
> fix: dataset page ux enhancement

- src/CompositionRoot.ts
- src/domain/entities/GlassModule.ts
- src/domain/repositories/GlassDashboardsRepository.ts
- src/domain/usecases/GetReportDashboardUseCase.ts
- src/domain/usecases/ValidateGlassModulesUseCase.ts
- src/webapp/hooks/useGlassReportDashboard.ts
- src/webapp/pages/reports/ReportsPage.tsx
> Fetch Dashboard id from datastore

- i18n/en.pot
- src/domain/usecases/SetUploadStatusUseCase.tsx
- src/webapp/components/upload-history/Filter.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/860qgj72c
> Populate upload status dropdown

- i18n/en.pot
- src/webapp/components/current-data-submission/StatusMap.ts
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/current-data-submission/overview/StatusDetails.ts
- src/webapp/pages/app/themes/dhis2.theme.ts
-   **Issue:** Closes #?https://app.clickup.com/t/85yw8j5gb
> fix: update status and button colors

- i18n/en.pot
- i18n/es.po
- src/webapp/components/reports/EmbeddedReport.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/860qaw2q5
> fix: enable add filter button for embedded reports

- src/webapp/components/app-bar/GlassAppBar.tsx
> fix: who logo click handling

- src/webapp/components/current-data-submission/StatusMap.ts
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/current-data-submission/overview/StatusDetails.ts
- src/webapp/components/module-card/ModuleCard.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/860qquh9c, https://app.clickup.com/t/860qqppfj
1. Added action required in open data submissions.
2. Fixed the questionnaire count in open data submissions
> feat: show action required on module cards

- src/webapp/components/current-data-submission/Advanced.tsx
-   **Issue:** Closes [[Bug Report] Change sentence ](https://app.clickup.com/t/860qqrvq1)
- Wording change
> fix: change sentence

- src/data/repositories/SampleDataCSVRepository.ts
-   **Issue:** Closes #?https://app.clickup.com/t/860qwenf3
set  NUMINFECTED column not mandatory
> fix: NUMINFECTED column not mandatory

- src/webapp/components/data-file-history/Filter.tsx
- src/webapp/components/data-submissions-history/DataSubmissionsHistoryContent.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/860qwem6f
history till 2016
> fix: history till 2016

- i18n/en.pot
- i18n/es.po
- src/CompositionRoot.ts
- src/data/repositories/UsersDefaultRepository.ts
- src/domain/repositories/UsersRepository.ts
- src/domain/usecases/SaveKeyDbLocaleUseCase.ts
- src/domain/usecases/SaveKeyUiLocaleUseCase.ts
- src/domain/usecases/SavePasswordUseCase.ts
- src/webapp/components/user-profile/UserProfileContent.tsx
- src/webapp/components/user-profile/UserSettingsContent.tsx
-   **Issue:** Closes [Make profile language selection actually change it in DHIS2 user](https://app.clickup.com/t/860qtpec7)
- Re-enable dropdowns, create logic, endpoint, repo to allow change to ui & db user language
*N/A*
> feat: allow change ui & database languages

- i18n/en.pot
- i18n/es.po
- src/webapp/components/current-data-submission/ListOfDatasets.tsx
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/landing-content/LandingContent.tsx
- src/webapp/components/landing-content/OpenDataSubmissions.tsx
- src/webapp/components/landing-content/notifications/YourNotifications.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/85yw8j5j8
> Empty datasets and empty open data submission handling.

- src/data/repositories/DataValuesDefaultRepository.ts
- src/data/repositories/SystemInfoDefaultRepository.ts
- src/domain/entities/data-entry/DataValuesSaveSummary.ts
- src/domain/entities/data-entry/ImportSummary.ts
- src/domain/repositories/SystemInfoRepository.ts
- src/domain/usecases/GetLastAnalyticsRunTimeUseCase.ts
- src/domain/usecases/data-entry/ImportRISFileUseCase.tsx
- src/webapp/components/current-data-submission/Validations.tsx
- src/webapp/components/reports/EmbeddedReport.tsx
- src/webapp/components/upload/ReviewDataSummary.tsx
- src/webapp/hooks/useGetLastSuccessfulAnalyticsRunTime.ts
-   **Issue:** Closes #?https://app.clickup.com/t/860qqcyxf
https://github.com/EyeSeeTea/glass-dev/assets/83749675/7f8686cd-3f6e-4212-87cf-64bc31d5c236
> fix: show validation report when ready on summary page

- i18n/en.pot
- src/webapp/components/current-data-submission/StatusMap.ts
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/current-data-submission/overview/CtaButtons.tsx
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/860qxapxh
> fix: buttons padding and bgcolor. Action req text

- i18n/en.pot
- src/domain/usecases/DownloadDocumentUseCase.ts
- src/domain/usecases/data-entry/ImportEGASPFile.ts
- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/utils/ModuleProperties.ts
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- https://app.clickup.com/t/860qwcnuw
- https://app.clickup.com/t/860qwcpb8
> delete confirmation text and some improvements.

- i18n/en.pot
- package.json
- src/data/repositories/InstanceDefaultRepository.ts
- src/data/repositories/bulk-load/EGASPProgramDefaultRepository.ts
- src/webapp/components/landing-content/LandingContent.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/86781xu0m
> fix: remove api in filter for perf improvements

- package.json
- src/data/repositories/CountryInformationDefaultRepository.ts
- src/data/repositories/TrackerDefaultRepository.ts
- src/domain/repositories/TrackerRepository.ts
- src/domain/usecases/data-entry/amr-i/ImportRISIndividualFile.ts
- yarn.lock
> feat:  integrate d2-api tracker api 

- i18n/en.pot
- src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
- src/domain/utils/ModuleProperties.ts
- src/utils/currentPeriodHelper.ts
- src/webapp/components/data-file-history/Filter.tsx
- src/webapp/components/data-submissions-history/hooks/usePopulateDataSubmissionHistory.ts
-   **Issue:** Closes https://app.clickup.com/t/860r7pcn6
> Set EGASP data submission period to Yearly

- src/data/repositories/MetadataDefaultRepository.ts
- src/domain/repositories/MetadataRepository.ts
- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
- src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
-   **Issue:** Closes [Check EGASP clinics are inside the proper country instead of checking that the OU inside the file and the country are the same](https://app.clickup.com/t/860rq571r)
> Check in EGASP upload document that clinic is inside clinics in the selected country

- i18n/en.pot
- i18n/es.po
- src/data/repositories/InstanceDefaultRepository.ts
- src/domain/entities/User.ts
- src/webapp/components/app-bar/GlassAppBar.tsx
- src/webapp/components/app-bar/OrgUnitSelector.tsx
- src/webapp/components/app-bar/SearchInput.tsx
- src/webapp/contexts/current-orgUnit-context.ts
-   **Issue:** Closes [Country dropdown to use shortname of OUs and have a search function](https://app.clickup.com/t/860rqejr6)
- Add shortName to fetching & adding to context;
- Create Search functionality
[screen-capture.webm](https://github.com/EyeSeeTea/glass-dev/assets/44171664/2c841a98-f037-4aae-80ab-35408e26aea6)
> Show orgUnit shortName & add search functionality

- src/data/repositories/Dhis2EventsDefaultRepository.ts
- src/data/repositories/download-empty-template/sheetBuilder.ts
- src/domain/usecases/data-entry/egasp/CustomValidationForEGASP.ts
-   **Issue:** Closes https://app.clickup.com/t/860rt219g
1. unique EGASP id validation within clinics
2. unique patient id and date combo validation within clinic
3. add lab_id column to egasp template
> custom validations should consider clinic as ou + add lab_id column to egasp template

- i18n/en.pot
- i18n/es.po
- src/webapp/components/private-route/PrivateRoute.tsx
> fix: revert incorrect access logic

- i18n/en.pot
- i18n/es.po
- package.json
- src/webapp/components/private-route/PrivateRoute.tsx
- Hotfix: revert changes in the redirection to home, to solve bug in all modules but EAR
> Release 1.3.4

- src/data/repositories/Dhis2EventsDefaultRepository.ts
- src/data/repositories/TrackerDefaultRepository.ts
- src/data/repositories/utils/TrackerPostResponseDefaultError.ts
-   **Issue:** Closes [Implement asynchronous import of events for EGASP](https://app.clickup.com/t/860rw47tv)
- async call to tracker related to EGASP import actions.
> EGASP - async import

- src/data/repositories/InstanceDefaultRepository.ts
- src/domain/entities/GlassModule.ts
- src/domain/entities/User.ts
- src/domain/usecases/data-entry/egasp/ImportEGASPFile.ts
- src/domain/utils/ModuleProperties.ts
- src/webapp/components/current-data-submission/overview/CurrentStatus.tsx
- src/webapp/components/data-file-history/Filter.tsx
- src/webapp/components/data-submissions-history/hooks/usePopulateDataSubmissionHistory.ts
- src/webapp/contexts/current-module-context.ts
- src/webapp/hooks/useGlassDataSubmissionsByModuleAndOU.ts
-   **Issue:** Closes 
- https://app.clickup.com/t/860r9xd21
- https://app.clickup.com/t/860rw486q
- https://app.clickup.com/t/860rw47x2
1. fetch populateCurrentYearInHistory from datastore and sort history by year
2. configure dataset string based on module.
3. Show line numbers for EGASP errors
https://www.awesomescreenshot.com/video/21633397?key=bf6ab5b8e0f780d233d9b2f64cdd63a6
https://www.awesomescreenshot.com/video/21633662?key=4fec57502c3b3781e36018eac2efea81
https://www.awesomescreenshot.com/video/21648079?key=7aaffdd8f4527aa0e86373e0b083dc5d
For EGASP error test : [PHL_CLN1_2021_all_WithErrsForTest1.xlsx](https://github.com/EyeSeeTea/glass-dev/files/12924926/PHL_CLN1_2021_all_WithErrsForTest1.xlsx)
> Misc bug fixes - EGASP

- src/data/repositories/RISDataCSVDefaultRepository.ts
- src/data/repositories/RISIndividualDataCSVDefaultRepository.ts
- src/data/repositories/SampleDataCSVDeafultRepository.ts
- src/data/repositories/SpreadsheetXlsxDefaultRepository.ts
- src/data/repositories/utils/CSVUtils.ts
- src/domain/repositories/SpreadsheetXlsxRepository.ts
- src/domain/usecases/data-entry/amr-i/ImportRISIndividualFile.ts
-   **Issue:** Closes [AMR Indiv: Remove Funghi variables update when uploading AMR Indiv data](https://app.clickup.com/t/860rv3g16)
- Add required attributes to TrackedEntities. From our tests, the current RIS file works for both AMR Individual and Funghi.
RIS file for testing purposes: 
[TEST_INDIVIDUAL_KOR_2021.txt](https://github.com/EyeSeeTea/glass-dev/files/13163458/TEST_INDIVIDUAL_KOR_2021.txt)
> AMR-Individual - Add required attributes to tracked entity

- src/CompositionRoot.ts
- src/data/repositories/RISIndividualFunghiDataCSVDefaultRepository.ts
- src/domain/entities/data-entry/amr-individual-funghi-external/RISIndividualFunghiData.ts
- src/domain/repositories/data-entry/RISIndividualDataRepository.ts
- src/domain/repositories/data-entry/RISIndividualFunghiDataRepository.ts
- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/ValidatePrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/amr-individual-funghi/ImportRISIndividualFunghiFile.ts
- src/domain/utils/ModuleProperties.ts
-   **Issue:** Closes [AMR Funghi: Implement file upload, datastore configuration](https://app.clickup.com/t/860rv3g56)
- Datastore user configuration
- Reuse & refactor of current AMR-Individual component for both Individual and Funghi uploads.
RIS file to test with: 
[TEST_FUNGHI_KOR_2021.txt](https://github.com/EyeSeeTea/glass-dev/files/13163449/TEST_FUNGHI_KOR_2021.txt)
> AMR-Funghi import

- src/data/repositories/GlassDataSubmissionDefaultRepository.ts
-   **Issue:** Closes [Remove EGASP current data submission cards from Home](https://app.clickup.com/t/860rygraa)
- Add exclusion list of modules to not show in open data submissions
> Remove EGASP open submission card in landing page

- src/domain/entities/Questionnaire.ts
- src/domain/usecases/GetAMCQuestionnaireListUseCase.ts
- src/domain/usecases/GetPopulatedProgramQuestionnaireUseCase.tsx
- src/domain/usecases/GetProgramQuestionnaireUseCase.tsx
- src/domain/usecases/data-entry/ImportProgramQuestionnaireDataUseCase.tsx
- src/webapp/components/current-data-submission/Questionnaires.tsx
- src/webapp/components/new-signal/ProgramQuestionnaireForm.tsx
- src/webapp/components/new-signal/hook/useProgramQuestionnaireForm.ts
- src/webapp/pages/new-signal/SignalPage.tsx
1. The general section of AMC Data Questionnaire is common to all Questionnaire parts
2. Disable the general section in all parts except the first one.
https://www.awesomescreenshot.com/video/23021958?key=01517c6dd91278ba515f8df3d7a0fbd0
> AMC data questionnaire, the general section should be common

- src/data/repositories/data-entry/RISIndividualFunghiDataCSVDefaultRepository.ts
- src/domain/entities/data-entry/amr-individual-funghi-external/RISIndividualFunghiData.ts
-   **Issue:** Closes #?https://app.clickup.com/t/860t0xyjt
added missing columns
[TEST_FUNGI_AGO_2022 copy.xlsx](https://github.com/EyeSeeTea/glass-dev/files/13650106/TEST_FUNGI_AGO_2022.copy.xlsx)
> add 3 missing columns to AMR-F

- src/scripts/cliAMC.ts
-   **Issue:** Closes [install Glass script](https://app.clickup.com/t/8693w8j2x)
- Delete while loop to use crontab instead in the execution of the recalculations script
> Delete while loop to use crontab instead in the execution of the recalculations script

- i18n/en.pot
- i18n/es.po
- src/webapp/components/current-data-submission/UploadsTable.tsx
-   **Issue:** Closes #? https://app.clickup.com/t/86947rg7q
- 86947rg7q
provide a one line explanation of each status
> feat: provide one line explanation of each status

- src/webapp/components/current-data-submission/UploadsTableBody.tsx
-   **Issue:** Closes #?https://app.clickup.com/t/8694g9jzc
- 8694g9jzc
1. fix: if there is an error on dhis data delete, do not delete the file
> fix: if there is an error on dhis data delete, do not delete the file

- src/data/repositories/download-template/DownloadTemplateDefaultRepository.ts
-   **Issue:** Closes #8694mxk9v [Bug: TEI missing in the raw product consumption stage excel file downloaded from the app](https://app.clickup.com/t/8694mxk9v)
- Change to correct name for tracked instance id in trackedEvents from DHIS2 
[AMC-PRODUCT-SUBMITTED-DZA-Populated (18).xlsx](https://github.com/EyeSeeTea/glass-dev/files/15465029/AMC-PRODUCT-SUBMITTED-DZA-Populated.18.xlsx)
[AMC-PRODUCT-CALCULATED-DZA-Populated (13).xlsx](https://github.com/EyeSeeTea/glass-dev/files/15465030/AMC-PRODUCT-CALCULATED-DZA-Populated.13.xlsx)
- Go to validation report in Algeria period 2021
- download submitted data and check
- download calculated data and check
[AMC-Product Level Data-DZA-TEMPLATE_2021.xlsx](https://github.com/EyeSeeTea/glass-dev/files/15465032/AMC-Product.Level.Data-DZA-TEMPLATE_2021. …
> Bug: TEI missing in the raw product consumption stage excel file downloaded from the app

- package.json
- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_validation.ts
-   **Issue:** Closes #https://app.clickup.com/t/8694g9jzc, #8694g9jzc
1. Script to detect data corruuption in AMR AGG glass module
2. Script to delete all AMR AGG data values for specified org unit and period - creates a JSON with updated values. Use Import/Export app to import this json with "delete"  option selected.
To detect data corruption run : yarn amr-agg-data-validation
`yarn amr-agg-data-validation -u 'https://dev.user:u5gdf6qnmbVUc9NXM!@dev.eyeseetea.com/who-dev-238'  `
To reset data values for specific period and org unit id:
`yarn amr-agg-data-reset -u 'https://dev.user:u5gdf6qnmbVUc9NXM!@dev.eyeseetea.com/who-dev-238' --orgUnit=IbGbsybdeou --period=2022 `
Upload the json using import export app :
> feat: Script to detect data corruption and reset data for AMR AGG

- README.md
- package.json
- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_validation.ts
-   **Issue:** Closes #8694g9jzc,  https://app.clickup.com/t/8694g9jzc
1. read url and auth details from .env file. 
The .env file should have a variable REACT_APP_DHIS2_BASE_URL pointing to the base url and a variable REACT_APP_DHIS2_AUTH with the username:password
> AMR AGG data validation and reset script - read auth and url from env file

- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_validation.ts
-   **Issue:** Closes #8694yzrz7 , https://app.clickup.com/t/8694yzrz7, 
1. validate amr agg data for each Org unit, period and batchId. 
To run the the reset script, pass batchId as parameter as well
`yarn amr-agg-data-reset --orgUnit=KwgjnBBpe5b --period=2022 --batchId=DS3`
> fix: when running validation script for AMR consider batchId as well

- package.json
- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_validation.ts
-   Fix: take batchID into account when deleting data in the GLASS script
> Release 1.6.7

- package.json
- src/scripts/amr_agg_data_reset_sample.ts
- src/scripts/amr_agg_data_validation_sample.ts
To run validation script for Sample file : 
`yarn amr-agg-data-validation-sample   `
To run reset script for Sample file: 
`yarn amr-agg-data-reset-sample --orgUnit=gb7vWtO7Wjp --period=2022 --batchId=DS1`
To run validation script for RIS file
`yarn amr-agg-data-validation-ris `
To run reset script for RIS file
`yarn amr-agg-data-reset-ris --orgUnit=wMTP4GblKr8 --period=2022 --batchId=DS1`
> feat: data validation and reset scripts for sample files

- i18n/en.pot
- i18n/es.po
- package.json
- src/domain/usecases/data-entry/amr/ImportRISFile.ts
- src/domain/usecases/data-entry/amr/ImportSampleFile.ts
- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_reset_sample.ts
- src/scripts/amr_agg_data_validation.ts
- src/scripts/amr_agg_data_validation_sample.ts
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/components/upload/SupportButtons.tsx
- src/webapp/components/upload/UploadContent.tsx
1. Scripts for Sample file error detection and reset.
2. Improve logging in scripts
3. On delete of sample, do not consider consistency checks
4. Run all consistency checks for import ignored for Sample file upload
5. Improve logging in scripts
6. Delete orphan sample files
7. Improve snackbar error messages, include error details
8. Fix status of SAMPLE uploads - set "IMPORTED" or "VALIDATED" for corresponding scenarios
9. Do not allow upload if SAMPLE file has blocking errors.
10. Cancel uplaod fix - the deleting of primary and secondary file was not done synchronously corrupting the datastore entries for uploads
> fix: delete orphan sample files and other fixes

- src/domain/usecases/data-entry/egasp/CustomValidationForEventProgram.ts
-   **Issue:** Closes #8694zpye9 [Bug: Substance level format: no calculated data](https://app.clickup.com/t/8694zpye9)
- Validate ATC version manual in substances files when uploading
> Validate ATC version manual in substances files when uploading

- package.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataAtcNotFound.json
- src/domain/usecases/data-entry/amc/utils/__tests__/data/rawSubstanceConsumptionDataBasic.json
- Quick hotfix in the AMC recalculation script
> Release 1.6.11

- src/domain/usecases/data-entry/amc/RecalculateConsumptionDataProductLevelForAllUseCase.ts
- src/domain/usecases/data-entry/amc/RecalculateConsumptionDataSubstanceLevelForAllUseCase.ts
- Wait 1 sec until next calculations execution and improve performance skipping if no data to calculate
This is the build of the script:
[glass-amc-recalculate-server.zip](https://github.com/user-attachments/files/16163823/glass-amc-recalculate-server.zip)
> Wait 1 sec until next calculations execution and improve performance skipping if no data to calculate

- .env
- package.json
- src/scripts/amr_agg_data_reset.ts
- src/scripts/amr_agg_data_reset_sample.ts
- src/scripts/amr_agg_data_validation.ts
- src/scripts/amr_agg_data_validation_sample.ts
- yarn.lock
-   **Issue:** Closes #86952j08z
- https://app.clickup.com/t/86952j08z
1. Call the datastore API only once in validation scripts.
2. Fetch url and auth from .env file using dotenv library
> fix: script perf enhancement + fetch env details from .env file

- i18n/en.pot
- i18n/es.po
- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/amc/CustomValidationsAMCProductData.ts
- src/domain/usecases/data-entry/amc/ImportAMCProductLevelData.ts
- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
- src/domain/usecases/data-entry/utils/getTEAValueFromOrganisationUnitCountryEntry.ts
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/components/upload/UploadFiles.tsx
- src/webapp/components/upload/UploadPrimaryFile.tsx
- src/webapp/components/upload/UploadSecondary.tsx
-   **Issue:** Closes #86955y9pc [Error with valid ISO3 codes for Manufacturer country](https://app.clickup.com/t/86955y9pc)
- Manufacturer country in AMC product should be an org unit code, add also custom validation
[AMC-PRODUCT-SUBMITTED-FRA-Populated (5).xlsx](https://github.com/user-attachments/files/16361045/AMC-PRODUCT-SUBMITTED-FRA-Populated.5.xlsx)
Custom validation:
[AMC-Product.Level.Data-FRA-TEMPLATE_TEST_MANUFACTURER.xlsx](https://github.com/user-attachments/files/16360819/AMC-Product.Level.Data-FRA-TEMPLATE_TEST_MANUFACTURER.xlsx)
[AMC-Product.Level.Data-FRA-TEMPLATE_TEST_MANUFACTURER_NOT_OK.xlsx](https://github.com/user-attachments/files/16360822/AMC-Product.Level.Data-FRA-TEMPLATE_TEST_MANUFACTURER_NOT_OK.xlsx)
> Error with valid ISO3 codes for Manufacturer country

- src/domain/utils/ModuleProperties.ts
-   **Issue:** Closes https://app.clickup.com/t/8695dbgzm,  #8695dbgzm
1. Change AMR-F completeStatusChange config
2. Make AMR-F Questionnaire mandatory in datatstore.
**NOTE**
Following datastore change required: 
Set glass --> modules --> AMR - Fungal --> questionnaires --> mandatory to true
Uploading AMR-F-Complete-on-Questionnaire.mov…
> fix: change AMR-F status on questionnaire completion

- src/CompositionRoot.ts
- src/data/repositories/CountryDefaultRepository.ts
- src/domain/entities/Country.ts
- src/domain/repositories/CountryRepository.ts
- src/domain/usecases/GetAllCountriesUseCase.ts
- src/domain/usecases/data-entry/ImportPrimaryFileUseCase.tsx
- src/domain/usecases/data-entry/amc/CustomValidationsAMCProductData.ts
- src/domain/usecases/data-entry/amc/ImportAMCProductLevelData.ts
- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
- src/domain/usecases/data-entry/utils/getTEAValueFromOrganisationUnitCountryEntry.ts
- src/utils/tests.tsx
- src/webapp/components/current-data-submission/UploadsTableBody.tsx
- src/webapp/components/upload/ConsistencyChecks.tsx
- src/webapp/components/upload/UploadFiles.tsx
- src/webapp/contexts/app-context.ts
- src/webapp/pages/app/App.tsx
-   **Issue:** Closes #8695gr7ee [https://app.clickup.com/t/8695gr7ee](https://app.clickup.com/t/8695gr7ee)
- Allow all countries in Manufacturer country in Product Register attributes
[AMC-Product Level Data-AFG-TEMPLATE (1).xlsx](https://github.com/user-attachments/files/16726207/AMC-Product.Level.Data-AFG-TEMPLATE.1.xlsx)
> Allow all countries in Manufacturer country in Product Register attributes

- package.json
- src/domain/usecases/data-entry/egasp/CustomValidationForEventProgram.ts
- src/webapp/pages/app/App.tsx
Fixes for the below : 
- url too long fix for egasp
- disable report bugs in prod
> Release 1.6.19 

- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
- src/domain/usecases/program-rules-processing/ProgramRuleValidationForBLEventProgram.ts
- src/domain/utils/ModuleProperties.ts
-   **Issue:** Closes #? https://app.clickup.com/t/86963xwby, #86963xwby, https://app.clickup.com/t/86969jxw1, #86969jxw1, https://app.clickup.com/t/86969jyth, #86969jyth
- 
1. Fixed null check for sample date in AMR-I import
2. Change AMR-I status on questionnaire complete
> fix: AMR I import fix and Status change on Questionnaire complete 

- package.json
- src/domain/usecases/data-entry/amr-individual-fungal/ImportRISIndividualFungalFile.ts
- src/domain/usecases/program-rules-processing/ProgramRuleValidationForBLEventProgram.ts
- src/domain/utils/ModuleProperties.ts
Fixes included in this release : 
Fix : Null check on AMR-I 
Fix: Status update on Questionnaire Completion for AMR-I
> Release 1.6.20

- src/domain/usecases/data-entry/ImportBLTemplateEventProgram.ts
accept all date formats for AMC substance
[AMC-Substance Level Data-CAN-TEMPLATE_2022.xlsx](https://github.com/user-attachments/files/17650387/AMC-Substance.Level.Data-CAN-TEMPLATE_2022.xlsx)
> fix: accept all date formats for AMC substance

- src/scripts/cliAsyncDeletions.ts
-   **Issue:** Closes #86961nyp4 [Bug: urgent Deleting Armenian AMC data in PROD failed (asyn deletion all modules)](https://app.clickup.com/t/86961nyp4)
:warning: METADATA CHANGE:
- key added to glass in datastore: https://dev.eyeseetea.com/who-dev-238/dhis-web-datastore/index.html#/edit/glass/async-deletions
[Screencast from 2024-10-29 13-18-27.webm](https://github.com/user-attachments/assets/cb7c8ba2-d89a-4491-ab70-913abb548406)
1. Click on trash icon in glass app
2. With the correct .env file run: `yarn start-async-deletions`
- For build and run in the server adding crontab config: `build-async-deletions` and you will get the .zip
> Bug: urgent Deleting Armenian AMC data in PROD failed (asyn deletion all modules)

- src/webapp/components/current-data-submission/UploadsTableBody.tsx
-   **Issue:** Closes #8697aj71v [Async uploads](https://app.clickup.com/t/8697aj71v)
- Change message when deleting an async upload: Upload cancelled
[Screencast from 2025-03-26 13-57-09.webm](https://github.com/user-attachments/assets/57f9f827-b2c8-4394-bf93-6bb890b42469)
> Change message when deleting an async upload
